<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\JobRepresentation[] $jobs
 */

// Copy of Omeka application/view/omeka/admin/job/browse.phtml, with added links.

use \Log\Stdlib\JobState;

$plugins = $this->getHelperPluginManager();
$url = $this->plugin('url');
$api = $this->plugin('api');
$i18n = $this->plugin('i18n');
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$jobState = $plugins->get('jobState');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$this->htmlElement('body')->appendAttribute('class', 'jobs browse');

$this->headLink()
    ->appendStylesheet($assetUrl('css/job.css', 'Log'));
$this->headScript()
    ->appendFile($assetUrl('js/job.js', 'Log'), 'text/javascript', ['defer' => 'defer']);

$stateLabels = array_map($translate, array_column(JobState::STATES, 'label', 's'));

$stateWarning = $escapeAttr($translate('Warning: The system state may not be reliable on some servers.'));
$stateWarning = sprintf(' title="%1$s" aria-label="%1$s"', $stateWarning);

$jobStateUrlBase = strtr($url('admin/job-state', ['id' => '0000']), ['0000' => '{id}']);
?>

<?php // Display the state below the status. ?>
<style>
    .system-state-header {
        float: right;
        font-weight: normal;
    }
    .flex-between .tablesaw-cell-content {
        flex-wrap: wrap;
        justify-content: space-between;
    }
    .flex-br {
        flex-basis: 100%;
        height: 0;
    }
</style>

<?= $this->pageTitle($translate('Jobs')) ?>

<div class="browse-controls">
    <?= $this->pagination() ?>
    <?= $this->browse()->renderSortSelector('jobs') ?>
</div>
<?php $this->trigger('view.browse.before'); ?>

<?php if (count($jobs)): ?>
<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th>
                <span><?= $translate('Id (Params)') ?></span>
                <span class="system-state-header"<?= $stateWarning ?>><?= $translate('System state') ?></span>
            </th>
            <th><?= $translate('Date') ?></th>
            <th><?= $translate('Class') ?></th>
            <th><?= $escape($translate('Status (Log)')) ?></th>
            <th><?= $translate('Owner') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($jobs as $job):
        $jobId = $job->id();
        if ($owner = $job->owner()) {
            $ownerText = $hyperlink($owner->email(), $url(
                'admin/id',
                ['controller' => 'user', 'action' => 'show', 'id' => $owner->id()]
            ));
        } else {
            $ownerText = $translate('[no owner]');
        }
        $totalLogs = $api->search('logs', ['job_id' => $jobId, 'limit' => 0])->getTotalResults();
        $step = method_exists($job, 'step') ? $job->step() : null;
        $state = $jobState($job);
        ?>
        <tr>
            <td class="job-state flex-between" data-job-id="<?= $jobId ?>" data-job-state="<?= $state ?>"<?php if ($state && $state !== 'Ended'): ?> data-job-state-url="<?= strtr($jobStateUrlBase, ['{id}' => $jobId]) ?>" <?php endif; ?>>
                <span><?= $job->link($jobId) ?></span>
                <?php if ($state): ?>
                <span class="system-state-icon <?= JobState::STATES[$state]['icon'] ?>" title="<?= $stateLabels[$state] ?>" aria-label="<?= $stateLabels[$state] ?>"></span>
                <?php endif; ?>
            </td>
            <td><?= $escape($i18n->dateFormat($job->started(), null, \Omeka\View\Helper\i18n::DATE_FORMAT_SHORT)) ?></td>
            <td><?= $escape($job->jobClass()) ?></td>
            <td class="job-status" data-job-id="<?= $job->id() ?>">
                <?php if ($totalLogs): ?>
                <?= $hyperlink($translate($job->statusLabel()), $url('admin/log/default', [], ['query' => ['job_id' => $jobId]]), ['class' => 'status-link log-link job-status-label']) ?>
                <?php else: ?>
                <span class="job-status-label" data-job-id="<?= $jobId ?>"><?= $escape($translate($job->statusLabel())) ?></span>
                <?php endif; ?>
                <?php if ($step): ?>
                <span> - </span>
                <span class="job-status-step"><?= $step; ?></span>
                <span> / </span>
                <span class="job-status-steps"><?= $job->totalSteps() ?></span>
                <?php endif; ?>
            </td>
            <td><?= $ownerText ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php $this->trigger('view.browse.after'); ?>
<div class="browse-controls">
    <?= $this->pagination() ?>
</div>

<?php else: ?>

<div class="no-resources">
    <p><?= $translate('Omeka could not find any jobs.') ?></p>
</div>

<?php endif; ?>
