<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\JobRepresentation $resource
 * @var \Omeka\Api\Representation\JobRepresentation $job
 * @var \Omeka\Form\ConfirmForm $confirmForm
 */

// Copy of Omeka application/view/omeka/admin/job/show.phtml, with a link added in the bottom.

use \Log\Stdlib\JobState;

$plugins = $this->getHelperPluginManager();
$url = $this->plugin('url');
$escape = $plugins->get('escapeHtml');
$jobState = $plugins->get('jobState');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$this->htmlElement('body')->appendAttribute('class', 'jobs show');

$hasProgress = method_exists($job, 'step');
if ($job->started()) {
    $started = $this->i18n()->dateFormat($job->started(), 'long', 'long');
    if ($hasProgress) {
        $step = $job->step();
        $totalSteps = $job->totalSteps();
        $progress = $totalSteps ? sprintf('%s / %s', $step, $totalSteps) : $translate('[undefined]');
    }
} else {
    $started = $translate('[not started]');
    $progress = '-';
}
if ($job->ended()) {
    $ended = $this->i18n()->dateFormat($job->ended(), 'long', 'long');
} else {
    $ended = $translate('[not ended]');
}
if ($owner = $job->owner()) {
    $ownerText = $this->escapeHtml($owner->email());
} else {
    $ownerText = $translate('[no owner]');
}

$state = $jobState($job);

$stateWarning = $escapeAttr($translate('Warning: The system state may not be reliable on some servers.'));
$stateWarning = sprintf(' title="%1$s" aria-label="%1$s"', $stateWarning);
?>

<style>
    .state-icon {
        margin-left: 12px;
    }
</style>

<?= $this->pageTitle('#' . $escape($job->id()), 1, $translate('Jobs')) ?>
<div id="page-actions">
    <?php if ('in_progress' == $job->status()): ?>
        <?= $this->form($confirmForm) ?>
    <?php endif; ?>
</div>

<dl class="job-metadata">
    <div class="meta-group">
        <dt><?= $translate('Status') ?></dt>
        <dd class="value"><?= $job->statusLabel() ?></dd>
    </div>
    <?php if ($state): ?>
    <div class="meta-group log-job">
        <dt><?= $translate('System state') ?></dt>
        <dd class="value job-state"<?php if (JobState::STATES[$state]['processing']): ?> data-job-state-url="<?= $escapeAttr($url('admin/job-state', ['id' => $job->id()])) ?>"<?php endif; ?> data-job-id="<?= $job->id() ?>"<?= $stateWarning ?>>
            <span class="system-state-label"><?= $translate(JobState::STATES[$state]['label']) ?></span>
            <span class="system-state-icon <?= JobState::STATES[$state]['icon'] ?>" title="<?= $translate(JobState::STATES[$state]['label']) ?>" aria-label="<?= $translate(JobState::STATES[$state]['label']) ?>"></span>
        </dd>
    </div>
    <?php endif; ?>
    <?php if ($hasProgress): ?>
    <div class="meta-group">
        <dt><?= $translate('Progress') ?></dt>
        <dd class="value"><?= $progress ?></dd>
    </div>
    <?php endif; ?>
    <div class="meta-group">
        <dt><?= $translate('Started') ?></dt>
        <dd class="value"><?= $started ?></dd>
    </div>
    <div class="meta-group">
        <dt><?= $translate('Ended') ?></dt>
        <dd class="value"><?= $ended ?></dd>
    </div>
    <div class="meta-group">
        <dt><?= $translate('Class') ?></dt>
        <dd class="value"><?= $job->jobClass() ?></dd>
    </div>
    <div class="meta-group">
        <dt><?= $translate('Owner') ?></dt>
        <dd class="value"><?= $ownerText ?></dd>
    </div>
    <div class="meta-group">
        <dt><?= $translate('Args') ?></dt>
        <?php if ($job->args()): ?>
            <?php $args = json_encode($job->args(), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_LINE_TERMINATORS); ?>
            <dd class="value"><pre><?= $escape($args) ?></pre></dd>
        <?php else: ?>
        <dd class="value"><?= $translate('[no args]') ?></dd>
        <?php endif; ?>
    </div>
    <div class="meta-group">
        <dt><?= $translate('Log') ?></dt>
        <dd class="value">
            <?php if ($job->log()): ?>
            <?= $hyperlink($translate('view log'),
                $url(null, ['action' => 'log'], true),
                ['target' => '_blank']) ?>
            <?php else: ?>
            <?= $translate('[no log]') ?>
            <?php endif; ?>
        </dd>
    </div>

    <div class="meta-group">
        <dt><?= $translate('Log (database)') ?></dt>
        <dd class="value">
            <?php $totalLogs = $this->api()->search('logs', ['job_id' => $job->id(), 'return_scalar' => 'id'])->getTotalResults(); ?>
            <?php if ($totalLogs): ?>
            <?= $hyperlink(sprintf($translate('View log (%d results)'), $totalLogs),
                $url('admin/log/default', [], ['query' => ['job_id' => $job->id()]])) ?>
            <?php else: ?>
            <?= $translate('[no log]') ?>
            <?php endif; ?>
        </dd>
    </div>
</dl>
