<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Log\Api\Representation\LogRepresentation $log
 */

use \Log\Stdlib\JobState;

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$i18n = $plugins->get('i18n');
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$this->headLink()
    ->appendStylesheet($this->assetUrl('css/job.css', 'Log'))
    ->appendStylesheet($assetUrl('css/log.css', 'Log'));
$this->headScript()
    ->appendFile($assetUrl('js/job.js', 'Log'), 'text/javascript', ['defer' => 'defer']);

$job = $log->job();
$owner = $log->owner();
$ownerText = $owner
    ? $hyperlink($owner->email(), $this->url('admin/id', ['controller' => 'user', 'action' => 'show', 'id' => $owner->id()]))
    : '';
$reference = $log->reference();

$state = $log->jobState();

$stateWarning = $escapeAttr($translate('Warning: The system state may not be reliable on some servers.'));
$stateWarning = sprintf(' title="%1$s" aria-label="%1$s"', $stateWarning);
?>

<div class="resource-details">
    <h3 class="o-title"><?= $escape(sprintf($translate('Log #%d on %s'), $log->id(), $i18n->dateFormat($log->created(), 'medium', 'medium'))) ?></h3>
    <div class="meta-group">
        <h4><?= $escape($translate('Severity')) ?></h4>
        <div class="value">
            <?= $escape($translate($log->severityLabel())) ?>
        </div>
    </div>
    <div class="meta-group">
        <h4><?= $escape($translate('Reference')) ?></h4>
        <div class="value">
            <?= $reference ? $escape($translate($reference)) : '-' ?>
        </div>
    </div>
    <div class="meta-group">
        <h4><?= $escape($translate('User')) ?></h4>
        <div class="value">
            <?= $ownerText ?: '<span>-</span>' ?>
        </div>
    </div>
    <div class="meta-group">
        <?php if ($job): ?>
        <h4><?= $escape(sprintf($translate('Job #%d'), $job->id())) ?></h4>
        <div class="value">
            <span class="job-status" data-job-id="<?= $job->id() ?>">
                <span class="job-status-title"><?= $translate('Status:') ?></span>
                <span class="job-status-label"><?= $translate($job->statusLabel()) ?></span>
            </span>
        </div>
        <?php if ($state): ?>
        <div class="value log-job">
            <span class="job-state" data-job-id="<?= $job->id() ?>" data-job-state="<?= $state ?>"<?php if ($state && $state !== 'Ended'): ?> data-job-state-url="<?= $escapeAttr($url('admin/job-state', ['id' => $job->id()])) ?>" <?php endif; ?><?= $stateWarning ?>>
                <span class="system-state-title"><?= $translate('System state:') ?></span>
                <span class="system-state-label"><?= $translate(JobState::STATES[$state]['label']) ?></span>
                <span class="system-state-icon <?= JobState::STATES[$state]['icon'] ?>" title="<?= $translate(JobState::STATES[$state]['label']) ?>" aria-label="<?= $translate(JobState::STATES[$state]['label']) ?>"></span>
            </span>
        </div>
        <?php endif; ?>
        <div class="value">
            <?= $escape(sprintf($translate('Started at %s'), $i18n->dateFormat($job->started(), 'medium', 'medium'))) ?>
        </div>
        <div class="value">
            <?= $escape(sprintf($translate('Ended at %s'), $job->ended() ? $i18n->dateFormat($job->ended(), 'medium', 'medium') : '-')) ?>
        </div>
        <div class="value">
            <?= $hyperlink($translate('Parameters'), $this->url('admin/id', ['controller' => 'job', 'action' => 'show', 'id' => $job->id()])) ?>
        </div>
        <?php if ($job->log()): ?>
        <div class="value">
            <?= $hyperlink($translate('Log'), $this->url('admin/id', ['controller' => 'job', 'action' => 'log', 'id' => $job->id()])) ?>
        </div>
        <?php endif; ?>
    <?php else: ?>
        <h4><?= $escape($translate('Job')) ?></h4>
        <div class="value">
            <span>-</span>
        </div>
    <?php endif; ?>
    </div>
    <div class="meta-group">
        <h4><?= $translate('Message') ?>
        <?php /*
        <span class="actions"><?= $hyperlink('', '#', [
            'class' => 'o-icon- fa fa-expand popover',
            'title' => $translate('Full log'),
        ]) ?>
        </span>
        */ ?>
        </h4>
        <div class="value log-message webui-popover-content">
            <?= $log->text() ?>
        </div>
    </div>
    <?php $this->trigger('view.details', ['entity' => $log]); ?>
</div>
